services:
  - type: web
    name: medical-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: ENV
        value: production
